### ISSUE TITLE
Definir o(s) mapa(s) do jogo

### ISSUE THREAD

**Issue by juliaschmitt09** [Hope-Games/Maze-of-the-past-#19]
Desenhar o mapa. Depende de #16

**Comment by leticiarfur** [comment]
O jogo se passa em dois ambientes, o primeiro será a casa do personagem Tyler, onde dará inicio a história. Já o segundo ambiente onde se passará efetivamente o labirinto do jogo se trata de uma chácara que pertence a família do Derek.
