### ISSUE TITLE
Programar o(s) mapa(s) do jogo

### ISSUE THREAD

**Issue by juliaschmitt09** [Hope-Games/Maze-of-the-past-#20]
- [x] Pesquisar por tiles genéricos;
- [x] Definir as camadas;
- [x] Dispor os tiles nas camadas;
- [x] Parametrizar o mapa;
- [x] Exportar o mapa;
- [x] Importar o mapa e suas camadas no jogo.

Depende de #19 
Referência: [OpenGameArt] (https://opengameart.org/).

**Comment by leticiarfur** [comment]
Usado o aplicativo [Tiled](https://www.mapeditor.org/) para edição do mapa em formato JSON.
